import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { driver } from 'driver.js';
import 'driver.js/dist/driver.css';
import '../css/app.css';
import { api } from './api';
import ChatPage from './components/ChatPage';
import AdminLiveChatPage from './components/AdminLiveChatPage';
import ProfilePage from './components/ProfilePage';

const componentMap = {
  ChatPage,
  AdminLiveChatPage,
  ProfilePage,
} as const;

const root = document.getElementById('react-page');
const propsNode = document.getElementById('page-props');

if (root) {
  const componentName = root.dataset.component as keyof typeof componentMap | undefined;
  const Component = componentName ? componentMap[componentName] : undefined;

  if (Component) {
    const props = propsNode?.textContent ? JSON.parse(propsNode.textContent) : {};
    createRoot(root).render(
      <StrictMode>
        {/* The page name and JSON props are generated by trusted server-side templates. */}
        <Component {...props} />
      </StrictMode>,
    );
  }
}

function startOnboarding(): void {
  if (document.body.dataset.onboarding !== 'pending') return;
  if (!document.querySelector('[data-tour="dashboard"]')) return;

  let completed = false;
  const markCompleted = async () => {
    if (completed) return;
    completed = true;
    document.body.dataset.onboarding = 'complete';
    try {
      await api('/client/onboarding/complete', { method: 'POST' });
    } catch {
      completed = false;
    }
  };

  const tour = driver({
    animate: true,
    showProgress: true,
    allowClose: true,
    overlayOpacity: 0.68,
    nextBtnText: 'Next',
    prevBtnText: 'Back',
    doneBtnText: 'Finish',
    progressText: '{{current}} of {{total}}',
    onDestroyed: () => void markCompleted(),
    steps: [
      {
        element: '[data-tour="dashboard"]',
        popover: {
          title: 'Welcome to 4BS Garage',
          description: 'This dashboard keeps your appointments, support conversations, and service follow-ups in one place.',
          side: 'right',
          align: 'start',
        },
      },
      {
        element: '[data-tour="appointment"]',
        popover: {
          title: 'Book an appointment',
          description: 'Choose a service, mechanic, vehicle, date, and available time slot.',
          side: 'right',
          align: 'start',
        },
      },
      {
        element: '[data-tour="chat"]',
        popover: {
          title: 'AI and live support',
          description: 'Ask the AI assistant first, then request an administrator when you need a person to join.',
          side: 'right',
          align: 'start',
        },
      },
      {
        element: '[data-tour="profile"]',
        popover: {
          title: 'Complete your profile',
          description: 'Update your contact details and upload a photo or take one using your camera.',
          side: 'right',
          align: 'start',
        },
      },
      {
        element: '[data-tour="dashboard-metrics"]',
        popover: {
          title: 'Track your service activity',
          description: 'See appointment totals and completed jobs that still need your rating.',
          side: 'bottom',
          align: 'start',
        },
      },
    ],
  });

  window.setTimeout(() => tour.drive(), 350);
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', startOnboarding, { once: true });
} else {
  startOnboarding();
}
